//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontEnd_Version1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserInfo
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("FaceBook ID")]
        public string Name { get; set; }
        public string MovieCategory { get; set; }
        public string Movies { get; set; }
        public Nullable<double> Gender { get; set; }
        [Required]
        public Nullable<double> Age { get; set; }
        public string keywords { get; set; }
        public Nullable<double> AvLikesCount { get; set; }
        public Nullable<double> AvHeartCount { get; set; }
        public Nullable<double> AvReviewPolarity { get; set; }
        public Nullable<double> AvThreadPolarity { get; set; }
        public string Movie1 { get; set; }
        public string Movie2 { get; set; }
        public string Movie3 { get; set; }
        public string Movie4 { get; set; }
        public string Movie5 { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string UserName { get; set; }
        [Required]
        public string Location { get; set; }
    }
}
